name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build --output type=image,push=true -t ghcr.io/${{ github.repository_owner }}/todoapp:latest .
          docker push ghcr.io/${{ github.repository_owner }}/todoapp:latest
